services:
  - type: web
    name: url-shortener
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install --include=dev && npm run build && npm prune --production
    startCommand: node dist/server.js